/**
 * Capital Crew — ZONE DOMINION + PRACTICE MODE
 *
 * DOMINION:
 *   A zone is "dominated" by a player when they own the most property in it
 *   (compared with the count of every other player's properties there).
 *   Each tick, the dominant player collects a "rent" tax equal to 10% of
 *   income generated by all OTHER players' properties in that zone.
 *
 *   - One zone can have only one dominant player.
 *   - If the dominant player is human, an owner icon appears on the zone.
 *   - The plaza is the highest-traffic zone — dominating it is the meta goal.
 *
 * PRACTICE MODE:
 *   Pre-game toggle that:
 *   - Removes the WIN/LOSE economy check
 *   - Disables AI opponents (they don't spawn)
 *   - Disables sabotage menu T button
 *   - Disables reactor emergencies
 *   - Disables assassin mode
 *   - Cash and properties still work, skills still train, just no end condition
 *
 *   Practice is selected from the role picker as a 4th option (special card).
 */
import { ZONES } from '../data/Properties';
import { humanPlayer, type PlayerState } from '../state/PlayerState';

export const DOMINION_TAX_PCT = 0.10; // 10% of opponents' income flows to dominator
export const DOMINION_MIN_OWNED = 2;  // Need to own at least N properties to dominate

export interface DominionState {
  zoneId: string;
  leaderId: string | null;
  leaderName: string | null;
  ownCount: number;
  /** Tax collected this tick. */
  lastTickTax: number;
}

/** Recompute dominion across zones at the start of any tick. */
export function computeDominion(
  players: PlayerState[],
): Map<string, DominionState> {
  const out = new Map<string, DominionState>();
  for (const zone of ZONES) {
    const counts: Record<string, { name: string; count: number }> = {};
    for (const p of players) {
      const c = p.ownedPropertyCountInZone(zone.id);
      if (c > 0) counts[p.id] = { name: p.name, count: c };
    }
    let leadId: string | null = null;
    let leadCount = DOMINION_MIN_OWNED - 1; // disqualifier threshold
    for (const [pid, info] of Object.entries(counts)) {
      if (info.count > leadCount) {
        leadCount = info.count;
        leadId = pid;
      }
    }
    // tiebreaker: skip (no dominator)
    const tie = Object.values(counts).filter((i) => i.count === leadCount).length > 1;
    if (tie) leadId = null;

    out.set(zone.id, {
      zoneId: zone.id,
      leaderId: leadId,
      leaderName: leadId ? counts[leadId]?.name ?? null : null,
      ownCount: leadCount,
      lastTickTax: 0,
    });
  }
  return out;
}

/** Apply the dominion tax. Returns total tax paid out. */
export function applyDominionTax(
  players: PlayerState[],
  dominion: Map<string, DominionState>,
  incomeByPlayer: Map<string, number>,
): number {
  const byId = new Map(players.map((p) => [p.id, p]));
  let total = 0;
  for (const dom of dominion.values()) {
    if (!dom.leaderId) continue;
    const leader = byId.get(dom.leaderId);
    if (!leader) continue;
    for (const [pid, inc] of incomeByPlayer.entries()) {
      if (pid === dom.leaderId) continue;
      const tax = Math.floor(inc * DOMINION_TAX_PCT);
      leader.cash += tax;
      dom.lastTickTax += tax;
      total += tax;
    }
  }
  return total;
}

/** Quick query: is the human player dominant anywhere? */
export function humanDominionZones(
  dominion: Map<string, DominionState>,
): string[] {
  const out: string[] = [];
  for (const dom of dominion.values()) {
    if (dom.leaderId === humanPlayer.id) out.push(dom.zoneId);
  }
  return out;
}
